# Generated by Django 5.1.6 on 2025-02-28 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_option",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="option1",
            field=models.CharField(default="Default Option 1", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="option2",
            field=models.CharField(default="Default Option 2", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="option3",
            field=models.CharField(default="Default Option 3", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="option4",
            field=models.CharField(default="Default Option 4", max_length=100),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="core.quiz",
            ),
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
