# Generated by Django 5.1.6 on 2025-03-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_scanrecord_unique_together'),
        ('core', '0004_alter_customuser_username'),
    ]

    operations = [
    ]
