# Generated by Django 5.1.6 on 2025-03-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20250323_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='diycreation',
            name='player',
        ),
        migrations.RemoveField(
            model_name='like',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='like',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerbadge',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerquiz',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='playertask',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playertask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='walkingdata',
            name='player',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='DIYCreation',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='PlayerBadge',
        ),
        migrations.DeleteModel(
            name='PlayerQuiz',
        ),
        migrations.DeleteModel(
            name='PlayerTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='WalkingData',
        ),
    ]
